name: Mise à jour du vote
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exécuter le script Python
      run: python vote_borda.py > winner.txt